# Generated by Django 4.2 on 2023-04-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues_created', to='user.user')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues_resolved', to='user.user')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
    ]
